DROP DATABASE IF EXISTS DNDcharacter_db;

CREATE DATABASE DNDcharacter_db;

USE DNDcharacter_db;

CREATE TABLE characters(
  id INTEGER AUTO_INCREMENT NOT NULL,
  name VARCHAR(100),
  class VARCHAR(100),
  race VARCHAR(100),
  STRENGTH INTEGER(10),
  DEXTERITY INTEGER(10),
  CONSTITUTION INTEGER(10),
  INTELLIGENCE INTEGER(10),
  WISDOM INTEGER(10),
  CHARISMA INTEGER(10),
  PRIMARY KEY (id)
);

CREATE TABLE race(
id INTEGER NOT NULL AUTO_INCREMENT,
race VARCHAR(10),
STR_mod INTEGER(10),
DEX_mod INTEGER(10),
CONST_mod INTEGER(10),
INT_mod INTEGER(10),
WIS_mod INTEGER(10),
CHAR_mod INTEGER(10),
PRIMARY KEY (id)
);

CREATE TABLE class(
id INT NOT NULL AUTO_INCREMENT,
Class VARCHAR(100),
Hit_die VARCHAR(100),
Primary_ability VARCHAR(100),
PRIMARY KEY (id)
);
